name: build parchiso per release
on:
  release:
    types:
      - created

env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}

jobs:
  build-nvidia:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages via Pacman
        run: pacman -Sy; pacman --noconfirm -S git archiso python python-pygithub github-cli p7zip
      - name: Replace packages and profile with Nvidia versions
        run: |
          cp iso/packages-nvidia.x86_64 iso/packages.x86_64
          cp iso/profiledef-nvidia.sh iso/profiledef.sh
      - name: Build Nvidia image
        run: mkarchiso -v iso/
      - name: Upload Nvidia iso to the release
        run: |
          cd ./out
          mkdir iso_parts
          7z -v1000m a iso_parts/"$(ls *.iso)".zip "$(ls *.iso)"
          md5sum $(ls *.iso) > iso_parts/iso-md5sums-nvidia.txt
          md5sum iso_parts/* > iso_parts/md5sums-nvidia.txt
          gh release upload ${{ github.event.release.tag_name }} ./iso_parts/* -R ${{ github.repository }}

  build-non-nvidia:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages via Pacman
        run: pacman -Sy; pacman --noconfirm -S git archiso python python-pygithub github-cli p7zip
      - name: Build non-Nvidia image
        run: mkarchiso -v iso/
      - name: Upload non-Nvidia iso to the release
        run: |
          cd ./out
          mkdir iso_parts
          7z -v1000m a iso_parts/"$(ls *.iso)".zip "$(ls *.iso)"
          md5sum $(ls *.iso) > iso_parts/iso-md5sums.txt
          md5sum iso_parts/* > iso_parts/md5sums.txt
          gh release upload ${{ github.event.release.tag_name }} ./iso_parts/* -R ${{ github.repository }}
